namespace Rsp.QuestionSetPortal.Models;

public class BaseContentObject
{
    /// <summary>
    /// Auto generate Id by the CMS
    /// </summary>
    public string? AutoGeneratedId { get; set; } = null!;
}