using Rsp.QuestionSetService.Models.UIContent;

namespace Rsp.QuestionSetService.Models
{
    public class SectionModel
    {
        public string? SectionName { get; set; }

        /// <summary>
        /// Auto generated by the CMS
        /// </summary>
        public string Id { get; set; } = null!;

        /// <summary>
        /// Manually assigned by a CMS user
        /// </summary>
        public string? SectionId { get; set; }

        /// <summary>
        /// Contains the questions in this section
        /// </summary>
        public IList<QuestionModel> Questions { get; set; } = new List<QuestionModel>();

        /// <summary>
        /// Contains UI content components in this section
        /// </summary>
        public IList<ContentComponent> GuidanceComponents { get; set; } = [];
    }
}