using Mapster;
using Rsp.QuestionSetService.Models;
using Rsp.QuestionSetService.Models.UIContent;
using Umbraco.Cms.Core.Models.Blocks;
using Umbraco.Cms.Web.Common.PublishedModels;

namespace Rsp.QuestionSetService.Helpers;

public static class ContentHelpers
{
    public static IList<QuestionModel> TransformQuestions(Section section, string version)
    {
        var result = new List<QuestionModel>();

        var sections = section?.Children<QuestionSlot>();

        if (sections != null)
        {
            foreach (var questionSlot in sections)
            {
                var associatedQuestion = questionSlot.QuestionContent as Question;
                var questionCategory = questionSlot.Category as Category;

                var questionModel = associatedQuestion.Adapt<QuestionModel>();

                questionModel.CategoryId = questionCategory?.CategoryId;
                questionModel.Version = version;
                questionModel.ValidationRules = TransformValidationRules(questionSlot);
                questionModel.Id = questionSlot.QuestionId;
                questionModel.AutoGeneratedId = questionSlot.Key.ToString();

                if (associatedQuestion != null)
                {
                    questionModel.Answers = TransformAnswers(associatedQuestion);
                    questionModel.Name = associatedQuestion.QuestionName;
                    questionModel.GuidanceComponents = associatedQuestion.GuidanceContent != null ? TransformUiComponent(associatedQuestion.GuidanceContent) : [];
                }

                result.Add(questionModel);
            }
        }

        return result;
    }

    public static IList<ContentComponent> TransformUiComponent(BlockListModel content)
    {
        var result = new List<ContentComponent>();
        foreach (var block in content)
        {
            switch (block.Content)
            {
                case AccordionComponent component:

                    if (component.Items != null)
                    {
                        var items = component.Items.Select(x => new AccordionComponentItemModel
                        {
                            Title = x.Content.Value<string>("title"),
                            Value = x.Content.Value<string>("value")
                        })?.ToList();

                        result.Add(new AccordionComponentModel { ContentType = component.ContentType.Alias, Items = items != null ? items : [] });
                    }

                    break;

                case DetailsComponent component:

                    result.Add(new DetailsComponentModel
                    {
                        ContentType = component.ContentType.Alias,
                        Title = component.Title,
                        Value = component.Value,
                    });

                    break;

                case BodyTextComponent component:

                    result.Add(new BodyTextComponentModel
                    {
                        ContentType = component.ContentType.Alias,
                        Value = component.Value,
                    });

                    break;

                case TabsComponent component:

                    if (component.Items != null)
                    {
                        var items = component.Items.Select(x => new TabComponentItemModel
                        {
                            Title = x.Content.Value<string>("title"),
                            Value = x.Content.Value<string>("value")
                        })?.ToList();
                        result.Add(new TabsComponentModel { ContentType = component.ContentType.Alias, Items = items != null ? items : [] });
                    }

                    break;
            }
        }
        return result;
    }

    public static IList<AnswerModel> TransformAnswers(Question question)
    {
        var result = new List<AnswerModel>();

        var answers = question.PossibleAnswers;
        if (answers != null)
        {
            foreach (var answer in answers)
            {
                var typedAnswer = answer as AnswerOption;
                var answerModel = new AnswerModel()
                {
                    AutoGeneratedId = typedAnswer?.Key.ToString(),
                    Id = typedAnswer?.OptionId,
                    OptionName = typedAnswer?.OptionName,
                };

                result.Add(answerModel);
            }
        }

        return result;
    }

    public static IList<RuleModel> TransformValidationRules(QuestionSlot question)
    {
        var result = new List<RuleModel>();

        var rules = question.ValidationRules;
        if (rules != null)
        {
            foreach (var rule in rules)
            {
                var strongRule = rule.Content as ValidationRule;

                if (strongRule != null)
                {
                    var ruleModel = strongRule.Adapt<RuleModel>();

                    ruleModel.QuestionId = question.QuestionId;
                    ruleModel.ParentQuestion = strongRule.ParentQuestion.Adapt<QuestionModel>();
                    if (ruleModel.ParentQuestion != null)
                    {
                        ruleModel.ParentQuestion.Name = strongRule.ParentQuestion.Value<string>("questionName");
                    }

                    ruleModel.Conditions = new List<ConditionModel>();

                    foreach (var condition in strongRule.Conditions)
                    {
                        var strongCondition = condition.Content as ValidationCondition;

                        var conditionModel = strongCondition.Adapt<ConditionModel>();

                        if (strongCondition?.ParentOptions != null)
                        {
                            conditionModel.ParentOptions = strongCondition.ParentOptions.Select(x => x.Adapt<AnswerModel>()).ToList();
                        }

                        ruleModel.Conditions.Add(conditionModel);
                    }
                    result.Add(ruleModel);
                }
            }
        }

        return result;
    }

    public static void PopulateGeneralQuestionSetMetadata(QuestionSetModel model, QuestionSet questionset)
    {
        model.Id = questionset.Key.ToString();
        model.Version = questionset.VersionNumber.ToString();
        model.Status = questionset.Status;
        model.ActiveFrom = questionset.ActiveFrom != DateTime.MinValue ? questionset?.ActiveFrom : null;
        model.ActiveTo = questionset?.ActiveTo != DateTime.MinValue ? questionset?.ActiveTo : null;
    }

    public static SectionModel PopulateSectionModel(Section section)
    {
        var category = section.Category as Category;
        var sectionModel = new SectionModel
        {
            SectionName = section.SectionName,
            Id = section.SectionId,
            AutoGeneratedId = section.Key.ToString(),
            GuidanceComponents = section.GuidanceContent != null ? ContentHelpers.TransformUiComponent(section.GuidanceContent) : [],
            CategoryId = category?.CategoryId
        };
        return sectionModel;
    }
}